- name: demo on filters/functions 
  hosts: local 
  connection: local 
  tasks: 
  - name: print the default variable 
    ansible.builtin.debug: 
      msg: "hello {{ course | default('Ansible')}}" 
  - name: convert to upper case 
    vars: 
      greeting: "Hello Ramesh"
    ansible.builtin.debug: 
      msg: " {{ greeting | upper }} "

  - name: convert to lower case 
    vars: 
      greeting: "Hello Ramesh"
    ansible.builtin.debug: 
      msg: " {{ greeting | lower }} " 

  - name: get unique number 
    vars: 
      number: [1,2,3,4,5,6,7,5,4,3,2,1,6]
    ansible.builtin.debug: 
      msg: " {{ number | unique}} "

  - name: get the min number 
    vars: 
      number: [10,9,20,3,1,2,4]
    ansible.builtin.debug:  
      msg: "{{ number | min }}"

  - name: get max the number 
    vars: 
      number: [10,9,20,3,1,2,4] 
    ansible.builtin.debug:  
      msg: "{{ number | max }}"

  - name: convert map to list 
    vars: 
      course: 
        name: "DevopsWithAWS" 
        duration: "120"
        trainer: "siva kumar" 
    ansible.builtin.debug: 
      msg: "{{ course | dict2items}}"
  
  - name: covert list to map 
    vars: 
      course:
        - { "key": "name","value": "DevopsWithAWS"}
        - { "key": "duration","vaule": 120}
        - { "key": "trainer","vaule": "siva kumar"}
    ansible.builtin.debug: 
      msg: "{{ course | items2dict }}"