- name: command vs shell 
  hosts: local 
  connection: local 
  tasks: 
  - name: print the shell module usage 
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # login to the server and execute the command 

  - name: print the command module usage 
    ansible.builtin.command: ps -ef | grep ssh 
    register: output 
    