- name: configure mysql server 
  hosts: mysql 
  become: yes  
  tasks: 
  - name: install the mysql server 
    ansible.builtin.package:
      name: mysql-server 
      state: present 
  - name: start the mysql server 
    ansible.builtin.service: 
      name: mysqld 
      state: started 